---
- name: Configure Dev Ubuntu Environment
  hosts: localhost
  become: yes

  tasks:
  - name: Packages are updated
    package:
      name: "*"
      state: latest

  - name: Packages Installed and Updated
    package:
      name:
        - vim
        - vim-syntastic
        - tmux
        - ansible
        - python3
        - python3-winrm
      state: latest

  - name: Directories Created
    file:
      path: "{{ item }}"
      state: directory
      owner: "{{ lookup('env', 'USER') }}"
      group: "{{ lookup('env', 'USER') }}"
      mode: '0755'
    loop:
      - /home/{{ lookup('env', 'USER') }}/projects
      - /home/{{ lookup('env', 'USER') }}/projects/python-dev
      - /home/{{ lookup('env', 'USER') }}/projects/ansible
      - /home/{{ lookup('env', 'USER') }}/.vim
      - /home/{{ lookup('env', 'USER') }}/.vim/autoload

  - name: vimrc-setup script is downloaded
    get_url:
      url: https://raw.githubusercontent.com/jkelley41/config/main/vimrc-setup.sh
      dest: /home/{{ lookup('env', 'USER') }}/vimrc-setup.sh
      owner: "{{ lookup('env', 'USER') }}"
      group: "{{ lookup('env', 'USER') }}"
      mode: '0744'

   - name: vimrc is configured for python
     shell: /home/{{ lookup('env', 'USER') }}/vimrc-setup.sh
      
   - name: vim-plug is downloaded
     get_url:
       url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
       dest: /home/{{ lookup('env', 'USER') }}/.vim/autoload/plug.vim
       owner: "{{ lookup('env', 'USER') }}"
       group: "{{ lookup('env', 'USER') }}"
       mode: '0744'

  - name: Add vim-plug to .vimrc
    blockinfile:
      path: /home/{{ lookup('env', 'USER') }}/.vimrc
      marker: '" {mark} ANSIBLE MANAGED BLOCK'
      block: |
        call plug#begin()
        call plug#end()
   
  - name: vimrc is configured for ansible
    lineinfile:
      path: /home/{{ lookup('env', 'USER') }}/.vimrc
      insertbefore: '^call plug#end()'
      line: "   Plug 'pearofducks/ansible-vim'"

  - name: vimrc is configured for powershell 
    lineinfile:
      path: /home/{{ lookup('env', 'USER') }}/.vimrc
      insertbefore: '^call plug#end()'
      line: "   Plug 'pprovost/vim-ps1'"

  - name: vim-plug plugins are installed
    shell: 'vim -E -s -c "source ~/.vimrc" -c PlugInstall -c qa'
    ignore_errors: yes

  - name: .bashrc contains common aliases
    lineinfile:
      path: /home/{{ lookup('env', 'USER') }}/.bashrc
      line: "{{ item }}"
      state: present
    loop:
      - "alias ap='ansible-playbook'"
      - "alias ad='ansible-doc'"
      - "alias ag='ansible-galaxy'"
      - "alias sshgit='ssh -i ~/.ssh/github_rsa git@github.com'"
      - "alias ..='cd ..'"
      - "alias ai='sudo apt install'"
      - "alias vimrc='vim ~/.vimrc'"
      - "alias bashrc='vim ~/.bashrc'"
