---
# tasks file for install-ssh-key

- name: Add SSH key to authorized keys
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup ('file', ssh_pub_key_path ) }}"

- name: Copy SSH keys to remote host 1/2
  copy:
    src: "{{ item }}"
    dest: "/root/.ssh/"
    owner: root
    group: root
    mode: '0600'
  loop:
    - "{{ ssh_pub_key_path }}"
    - "{{ ssh_priv_key_path }}"
  when: ansible_user == 'root'

- name: Copy SSH keys to remote host 2/2
  copy:
    src: "{{ item }}"
    dest: "/home/{{ ansible_user }}/.ssh/"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
  loop:
    - "{{ ssh_pub_key_path }}"
    - "{{ ssh_priv_key_path }}"
